### ISSUE TITLE
Not working with Spree

### ISSUE THREAD

**Issue by abdul-shajin** [AlexanderZaytsev/SublimeText2RailsFileSwitcher#12]
Since I am using edge version of spree-commerce, I've loaded full gem files and project files to ST2 and when I tried to open controller files,it is creating a new file which aren't exist.

eg:
I hit super + 1 from rails/spree/sandbox/app/views/static_pages/help.html 
it creates and opens a file in rails/spree/app/controllers/static_controller.rb 
instead of opening rails/spree/sandox/app/controller/static_controller

Any solution??

**Comment by AlexanderZaytsev** [comment]
Could you explain the problem once again? What is it exactly? That the `/sandbox/` in the path gets lost?

**Comment by abdul-shajin** [comment]
No need to care about this. Spree commerce was not a rails app skeleton. You can close this now.
