### ISSUE TITLE
Singular controller name

### ISSUE THREAD

**Issue by nou-laif** [AlexanderZaytsev/SublimeText2RailsFileSwitcher#13]
When controller name is singular (e.g. UserController) it will try go to "app/views/users" instead of "app/views/user".

**Comment by AlexanderZaytsev** [comment]
Fixed in https://github.com/AlexanderZaytsev/SublimeText2RailsFileSwitcher/commit/d9f9b53bd9a164131a354b9a8686292f0f0ec737
