### ISSUE TITLE
RSpec Support

### ISSUE THREAD

**Issue by theo-bittencourt** [AlexanderZaytsev/SublimeText2RailsFileSwitcher#16]
Is there a plan to support RSpec files?

Thanks in advance!

**Comment by AlexanderZaytsev** [comment]
Yes, I'm planning to support it soon.

**Comment by theo-bittencourt** [comment]
;)

**Comment by AlexanderZaytsev** [comment]
I will keep it open until I solve the issue.

**Comment by AlexanderZaytsev** [comment]
Added in https://github.com/AlexanderZaytsev/SublimeText2RailsFileSwitcher/commit/07d7dacad85a23d1864fb08c215dbe32a881dbf9

**Comment by theo-bittencourt** [comment]
Thanks so much!
