### ISSUE TITLE
Wrong folder name

### ISSUE THREAD

**Issue by ccodre** [AlexanderZaytsev/SublimeText2RailsFileSwitcher#2]
The plugins finds the right path to the requested file only if the rails app is the first one in the open folders list.

This is the output I get when I'm on my model:
`/home/ccodre/Code/php/phototo/app/controllers/tasks_controller.rb not found`

Phototo is a PHP app.

**Comment by AlexanderZaytsev** [comment]
Fixed in https://github.com/AlexanderZaytsev/SublimeText2RailsFileSwitcher/commit/e7bae9f4cbf166d7d23754c48bba56e2046c5ad6
