### ISSUE TITLE
Namespaced files aren't working

### ISSUE THREAD

**Issue by deiga** [AlexanderZaytsev/SublimeText2RailsFileSwitcher#5]
I have a Foo::Bar model in models/foo/bar.rb and it will open the controller in controllers/bar_controller.rb instead of controllers/foo/bar.rb

**Comment by AlexanderZaytsev** [comment]
Thanks for letting me know. This is now fixed in https://github.com/AlexanderZaytsev/SublimeText2RailsFileSwitcher/commit/1406c4895341abc69d16d985d97f64cfb23e8f99
