### ISSUE TITLE
rails file switcher  can't find model from controller or view if using namspace,  vice versa.

### ISSUE THREAD

**Issue by cod7ce** [AlexanderZaytsev/SublimeText2RailsFileSwitcher#7]
like title

**Comment by AlexanderZaytsev** [comment]
Could you provide an example of your namespace?

**Comment by cod7ce** [comment]
![rails_with_namespace](https://f.cloud.github.com/assets/1230025/221240/738af80e-8591-11e2-9c68-6003fbec2004.png)

**Comment by AlexanderZaytsev** [comment]
Well, I see why it's not working. If you are in the `Admin::UsersController`, then it expects a `Admin::User` model, not `User` (as you have). I'll see what can be done about this. Thanks for letting me know!

**Comment by AlexanderZaytsev** [comment]
@cod7ce could you try with the latest version tomorrow (tomorrow is when I expect it to be updated in Package Control)?
