### ISSUE TITLE
Feature request: Create missing view

### ISSUE THREAD

**Issue by deiga** [AlexanderZaytsev/SublimeText2RailsFileSwitcher#9]
I'd be great if RFS would ask me to create the view for the selected action if it can't find any.
(Of course make it say which view it would create)

**Comment by AlexanderZaytsev** [comment]
Nice idea! Added it in https://github.com/AlexanderZaytsev/SublimeText2RailsFileSwitcher/commit/9514961bff893314e116d78b4b1f375d3a429bbb
